version: "3.9"
services:
  # nestjs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nestjs
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_USERNAME=sgbidev
  #     - DB_PASSWORD=sgbidev2023*
  #     - DB_DATABASE=SGBI
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  #     - redis
  postgres:
    image: postgres
    container_name: sgbi-postgres
    environment:
      - POSTGRES_USER=sgbidev
      - POSTGRES_PASSWORD=sgbidev2023*
      - POSTGRES_DB=SGBI
      - TZ=America/Caracas
    ports:
      - 5432:5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: sgbi-redis
    ports:
      - 6379:6379

volumes:
  pgdata:
